services:
  postgres:
    image: postgres:latest
    env_file:
        - .env
    container_name: calculatorDb
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  apicalculator:
    build:
      context: .
      dockerfile: ApiCalculator/Dockerfile
    container_name: apicalculator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5002
    ports:
      - "5002:5002"
    depends_on:
      - postgres

volumes:
  postgres_data: