services:
  postgres:
    image: postgres:latest
    container_name: calculatorDb
    environment:
      POSTGRES_USER: adjustmentsapp
      POSTGRES_PASSWORD: 1Password
      POSTGRES_DB: dump
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  apicalculator:
    build:
      context: .
      dockerfile: ApiCalculator/Dockerfile
    container_name: apicalculator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data: